### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by monchee** [mdiller/MangoByte#16]
Hi, I'd like to try this out, but I'm a noob with setting this up. I did a git clone, tried running it, and it wouldn't start. What am I missing?

**Comment by monchee** [comment]
Nevermind, I got it working in our Discord channel. Thanks!

**Comment by mdiller** [comment]
Whoops, I didn't see that you opened an issue about this, my bad. I really should add a quick installation instructions to the readme, but I'm glad you got it working!

**Comment by monchee** [comment]
That's okay! The bot has been great! 

I've added some audio clips from @midormeepo's site, soundsofdota.com. I actually suggested that it would be nice to add those to a Discord bot. https://twitter.com/midormeepo/status/763713754630684672

My users have been having fun with it all the time. Thanks for a great bot!

**Comment by mdiller** [comment]
Oh nice, I might do that.

Glad to hear it! No problemo!
