### ISSUE TITLE
[TTS] "m." causes the bot to get all French.

### ISSUE THREAD

**Issue by VixusFoxy** [mdiller/MangoByte#20]
What's happening is "m."  is being parsed as "Monsieur" by the bot. 

Input:
"?tts What about him."

Output: What about himmonsieur. 

Also, I think the language DB from back in May is outdated.

**Comment by VixusFoxy** [comment]
I see!

Does that mean the 'new' voices also have been added to it? Like, the
various male voices that were added to Google's assistants a while ago?



Op ma 15 okt. 2018 om 21:22 schreef Malcolm Diller <notifications@github.com

**Comment by mdiller** [comment]
Were they added languages? If so then yep those should be usable!

**Comment by mdiller** [comment]
I've merged the fix for this and it looks to be working fine now!
