### ISSUE TITLE
Bot keeps rejoining voice channel

### ISSUE THREAD

**Issue by TNSelahle** [mdiller/MangoByte#26]
### Steps to reproduce:
- Join voice channel and summon bot by `?summon`
- Unsummon the bot by `?unsummon`

The bot will leave the voice channel and rejoin it within 10 seconds. After a minute or so, it will leave again and rejoin. It just keeps doing this over and over.

**Comment by mdiller** [comment]
Sorry for taking a bit to respond to this issue. I've been out of internet range for the last week. 

This is a known issue. It is related to the way the discord.py library I'm using handles different types of closed signals for webhooks. I've created [this issue](https://github.com/Rapptz/discord.py/issues/3994) with the information that I have about it, but haven't gotten any direct responses. It looks like the library will be doing an update (v1.4) which includes some changes to the autoshardedclient that may help with the connection issues. My current plan for resolving this is to wait for that update (should be coming "soon") and try it to see if it fixes the problem. If it doesn't, I'll dive into trying to figure out exactly what's going on and see if I can make a pull request to the framework library to address it.

**Comment by TNSelahle** [comment]
Okay, thank you. I'll close this issue then.
