### ISSUE TITLE
Make linking your Steam account to the bot more user friendly

### ISSUE THREAD

**Issue by DMzda** [mdiller/MangoByte#34]
The bot was recently added to a server I'm in and I saw that some users struggled to find their friend code with the first try, or tried to use non accepted inputs such as their steam profile URL.

My 2 suggestions would be:
- Simplify the command so it could be `?link` or `?steam` instead of `?userconfig steam`
- Accept a larger range of input for the Steam ID. Expanding this to include any representation of the steam ID (you can use [the `steam` library](https://steam.readthedocs.io/en/latest/api/steam.steamid.html) for this) as well as Opendota and Dotabuff URLs would be ideal.

Thanks!

**Comment by mdiller** [comment]
I'll take a look! I think I'll not be using the steam library because it wont work well for the asyncio stuff, but i could definetly add a few more format options and possibly aliases for the command too.

**Comment by mdiller** [comment]
Hey so I implemented some more accepted formats for this, you can use a steam, dotabuff, or opendota url. It works with steam64 and steam32 ids. Note that it won't work for steam profile urls that have the name in the url. I think this will work for most people's use cases. I'd rather not make alias commands for stuff that already exist, but i could look into it more if i get more people suggesting it.
