### ISSUE TITLE
[Feature Request] parselm command

### ISSUE THREAD

**Issue by SirFireball3521** [mdiller/MangoByte#35]
There should be a 'parse last match' command, which parses the last match of the linked account. This would simplify running `lm` and then `parse`.

**Comment by mdiller** [comment]
Hey! So [opendota](https://www.opendota.com/) (the site i get all the dota match info from) actually has this cool feature where if you log in to their website, it will automatically parse all your matches for you. You don't have to create an account or anything, its just logging in via your steam account. Is there a reason this wouldn't work for what you want? I'd rather not add un-needed commands when stuff like this exists.

**Comment by SirFireball3521** [comment]
I have that enabled, but in my experience it can take up to a half an hour for the automatic parsing to get around to my replay. It works, but it's sometimes slow.

**Comment by mdiller** [comment]
I've implemented this in the latest round of bugfixes and small improvements. It's implemented by just making `?parse` automatically use your last match if no arguments are given.
