### ISSUE TITLE
porting to telegram

### ISSUE THREAD

**Issue by Geczy** [mdiller/MangoByte#72]
thoughts on a telegram port? im happy to begin the initiative. im hoping for a way to do this while keeping the fork in sync. like is mangobyte separated enough from the discord logic to allow for that?

**Comment by mdiller** [comment]
Unfortunatley mangobyte is veeeerry tied to the discord framework and logic. It'd be a pretty monumental effort to port to telegram and then also keep the discord branch in sync.
